app <- ShinyDriver$new("../")
app$snapshotInit("dq_drawertest")

app$snapshot()
app$executeScript("$('.dqdrawer-button')[0].click();")
app$executeScript("$('.dqdrawer-button')[5].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('.dqdrawer-wrapper').click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('.dqdrawer-button')[6].click();")
app$executeScript("$('.dqdrawer-button')[10].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('.dqdrawer-wrapper').click();")
app$waitFor("false", timeout = 300)
app$snapshot()
