app <- ShinyDriver$new("../")
app$snapshotInit("dq_handsontableTest")

app$snapshot(screenshot = FALSE)
app$setInputs(filter_rand_B = "f")
app$setInputs(sel_rand_pageSize = "5")
app$snapshot(screenshot = FALSE)
# app$setInputs(filter_rand_C = c(1, 36))
app$setInputs(filter_rand_D = "564")
app$snapshot(screenshot = FALSE)
app$setInputs(filter_rand_B = "")
app$setInputs(filter_rand_D = "")
app$setInputs(sel_rand_pageSize = "25")
app$setInputs(num_rand_page = 3)
app$setInputs(filter_rand_A = "world!")
app$snapshot(screenshot = FALSE)
