app <- ShinyDriver$new("../")
app$snapshotInit("displaytest")

app$snapshot()
app$setInputs(hide = "click")
app$snapshot()
app$setInputs(show = "click")
app$snapshot()
app$setInputs(toggle = "click")
app$snapshot()
app$setInputs(toggle = "click")
app$setInputs(toggle_cond = "click")
app$setInputs(condition = TRUE)
app$setInputs(toggle_cond = "click")
app$snapshot()
app$setInputs(condition = FALSE)
app$setInputs(toggle_cond = "click")
app$snapshot()
app$setInputs(toggle_all = "click")
app$snapshot()
