app <- ShinyDriver$new("../")
app$snapshotInit("autocomplete_inputTest")

app$snapshot(screenshot = FALSE)
app$setInputs(auto1 = "just")
app$snapshot(screenshot = FALSE)
app$setInputs(auto2 = "field")
app$snapshot(screenshot = FALSE)
app$setInputs(calc = "click")
app$snapshot(screenshot = FALSE)
app$setInputs(auto3 = "Ford Pantera L")
app$snapshot(screenshot = FALSE)
