app <- ShinyDriver$new("../")
app$snapshotInit("dq_gallerytest")

app$snapshot()
app$executeScript("$('.dqgallery-next')[0].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('.dqgallery-prev')[0].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('#prev')[0].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$executeScript("$('#show3')[0].click();")
app$waitFor("false", timeout = 300)
app$snapshot()
app$stop()
